apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: event-driven-workflow-
spec:
  entrypoint: event-driven-task
  templates:
  - name: event-driven-task
    steps:
    - - name: hello
        template: echo-template
  - name: echo-template
    inputs:
      parameters:
      - name: message
        value: Hello Argo Workflow!
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
